name: pgmorl
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2019.11.28
  - cpuonly=1.0
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - glib=2.63.1
  - graphite2=1.3.13
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2020.0
  - jasper=2.0.14
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1
  - patchelf=0.10
  - pcre=8.43
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - py-opencv=3.4.2
  - python=3.7.6
  - pytorch=1.4.0
  - readline=7.0
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.5.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - backcall==0.2.0
    - cffi==1.14.0
    - cloudpickle==1.2.2
    - cycler==0.10.0
    - cython==0.29.15
    - decorator==4.4.2
    - fasteners==0.15
    - future==0.18.2
    - glfw==1.10.1
    - gym==0.15.3
    - imageio==2.6.1
    - ipython==7.15.0
    - ipython-genutils==0.2.0
    - jedi==0.17.0
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - monotonic==1.5
    - mujoco-py==2.0.2.9
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.5
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - pycparser==2.19
    - pyglet==1.4.10
    - pygments==2.6.1
    - pyparsing==2.4.6
    - python-dateutil==2.8.1
    - pyyaml==5.3
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - sklearn==0.0
    - tensorboardx==2.0
    - traitlets==4.3.3
    - wcwidth==0.2.4
