#######################################
###       Logging Configuration     ###
#######################################
expt:
  project_name:                 "searl"
  session_name:                 "neuroevolution"
  experiment_name:              "default_searl_td3"


#######################################
###      NEVO Configuration         ###
#######################################
nevo:
  population_size:              6
  tournament_size:              2
  selection:                    True
  mutation:                     True
  training:                     True
  elitism:                      True
  min_train_time:               200
  worker:                       2
  reuse_batch:                  1
  ind_memory:                   False
  init_random:                  False


mutation:
  no_mutation:                  0.0
  parameters:                   1.0
  architecture:                 0.0
  activation:                   1.0
  rl_hyperparam:                1.0
  rl_hp_selection:              ['lr_actor','lr_critic'] # 'train_frames_fraction','batch_size',,'td3_policy_noise','td3_update_freq', 'optimizer']
  new_layer_prob:               0.0
  mutation_sd:                  0.1


train:
  replay_memory_size:           500000
  num_frames:                   1000000
  td3_double_q:                 True
  evo_warm_up:                  1
  min_train_steps:              2


rl:
  train_frames_fraction:        0.5
  gamma:                        0.99
  tau:                          0.005
  batch_size:                   32
  lr_actor:                     0.001
  lr_critic:                    0.001
  clip_grad_norm:               100
  td3_policy_noise:             0.2     # False or TD3 default: 0.2
  td3_noise_clip:               0.5     # default 0.5
  td3_update_freq:              2       # 1 or TD3 default: 2
  optimizer:                    "adam" ##  ["adam", "adamax", "rmsprop", "sdg"]
  start_timesteps:              1


seed:
  replay_memory:                20520864
  evaluation:                   20520864
  mutation:                     20520864
  training:                     20520864
  torch:                        20520864
  numpy:                        20520864


#######################################
###    Environment Configuration    ###
#######################################
env:
  name:                        'Humanoid-v4'


eval:
  eval_episodes:                1
  min_eval_steps:               1
  exploration_noise:            0.1     # Default 0.1
  test_episodes:                0
  test_seed:                    20520864


#######################################
###  Actor Starting Configuration   ###
#######################################
actor:
  hidden_size:             [128,128,128]
  activation:              'relu' #'relu' , 'sigmoid' 'softplus',
  output_activation:       'tanh'
  layer_norm:              True
  output_vanish:           False

#######################################
###  Critic Starting Configuration  ###
#######################################
critic:
  hidden_size:             [128,128,128]
  activation:              'relu' #'relu' , 'sigmoid' 'softplus',
  output_activation:       'linear'
  layer_norm:              True
  output_vanish:           True
